# Glossário {-}

## Descrição {-}

Nesse glossário, resumimos os principais conceitos e definições dos termos utilizados no texto principal que possam ser desconhecidos ou pouco claros para alguns leitores(as).

- **Abundance-based Coverage Estimator (ACE)**: estimador de riqueza de espécies baseado na abundância de espécies raras  
- **Agregação (raster)**: aumentar o tamanho dos pixels (diminuindo a resolução) de um raster, agregando os valores dos pixels em um pixel maior
- **Agrupamento filogenético**: espécies coexistindo nas comunidades são mais aparentadas do que esperado pelo acaso
- **Akaike Information Criterion (AIC)**: é uma métrica para seleção de modelos. Ele é usado para determinar qual entre os múltiplos modelos é o mais provável de prever dados observados ponderando essa previsão pelo número de parâmetros dos modelos. Os menores valores de AIC representam modelos com maior qualidade e simplicidade
- **Alinhamento (raster)**: ajusta o tamanho do pixel, extensão, número e origem dos pixels para várias camadas rasters
- **Ambiente ou *Environment* (RStudio)**: porção onde os objetos criados são armazenados
- **Amostra**: subconjunto da população, selecionados por um processo adequado de amostragem, utilizado para estimar características de toda a população
- **Análise de covariância (ANCOVA)**: é uma extensão da ANOVA com a adição de uma covariável medida em todas as unidades amostrais
- **Análise de variância (ANOVA)**: é um teste estatístico que avalia se há diferenças entre as médias de três ou mais grupos independentes. Existem uma variedade de delineamentos experimentais como - ANOVA de um fator, ANOVA de dois fatores, ANOVA em blocos aleatorizados, ANOVA de medidas repetidas e ANOVA *split-splot* - que diferem na maneira que o teste estatístico e os graus de liberdade são calculados
- **Análise paramétrica**:  assume que os dados foram amostrados de uma distribuição de forma conhecida (e.g., gaussiana, poisson, etc) e estima os parâmetros (e.g., média, desvio padrão, etc) da distribuição a partir dos dados
- **Análise não paramétrica**:  não pressupõe que os dados foram amostrados de uma distribuição de forma conhecida (e.g., gaussiana, poisson, etc) 
- **Array**: classe de objetos que representa elementos de um único modo no formato de combinação de tabelas, com linhas, colunas e dimensões
- **Árvore filogenética**: são hipóteses que representam o relação de parentesco entre as espécies (pode ser também indivíduos, genes, etc.) com informações sobre quais espécies compartilham um ancestral comum e a distância (tempo, genética, ou diferenças nos caracteres) que as separam
- **Atributo funcional**: uma propriedade mensurável dos organismos (geralmente em nível individual) que representa características morfológicas, fisiológicas ou fenológicas que afetam a aptidão alterando aspectos do crescimento, reprodução e sobrevivência
- **Atributos dos objetos**: são o modo (natureza) e a estrutura (organização) dos elementos nos objetos
- **Bloco (ANOVA)**: é uma área ou período de tempo dentro do qual as condições ambientais são relativamente homogêneas. O objetivo do uso dos blocos é controlar fontes de variações indesejadas na variável dependente que não são de interesse do pesquisador
- **Bootstrap**: estimador de riqueza de espécies que estima os parâmetros de uma população por reamostragens
- **Buffer (vetor)**: polígono que representam a área dentro de uma determinada distância de um dado vetorial, podendo ser a partir de um ponto, linha ou polígono
- **Camada (vetor ou raster)**: termo geral, mas geralmente associada à diferentes rasters reunidos num mesmo arquivo
- **Centroide (vetor ou raster)**: ponto central de uma feição vetorial ou o centro do pixel do raster
- **Chao 1**: estimador de riqueza de espécies baseado na abundância das espécies singleton e doubletons dentro de uma amostra 
- **Chao 2**: estimador de riqueza de espécies baseado na incidência (presença e ausência) das espécies singleton e doubletons dentro de uma amostra 
- **Clado**: um grupo de espécies aparentadas descendendo de um único nó na filogenia
- **Coeficiente de correlação**: indica a força da relação linear entre as duas variáveis
- **Coerção (linguagem R)**: transformação dos modos dos elementos seguindo uma hierarquia: character > double > integer > logical
- **Community Mean Nearest Taxon Distance (COMDISTNT)**: métrica de diversidade beta que calcula a média da distância filogenética/funcional entre o táxon mais próximo das espécies de duas comunidades
- **Community Mean Pairwise Distance (COMDIST)**: métrica de diversidade beta que calcula a média da distância filogenética/funcional entre as espécies de duas comunidades
- **Console (RStudio)**: onde a versão da linguagem R instalada é carregada para executar os códigos no RStudio
- **Conversão (linguagem R)**: transformação dos modos ou estrutura dos elementos de um objeto a partir de funções específicas
- **Conversões raster-vetor**: transformar dados vetoriais em rasters (rasterização) e transformar rasters em vetores (vetorização)
- **Convex Hull**: medida multivariada derivada da computação geométrica que calcula o espaço dos atributos de uma espécie ou de várias espécies em uma comunidade
- **Correlação**: é um teste que mede a força relativa da relação linear entre duas variáveis contínuas. A análise de correlação não assume que a variável X influencie a variável Y, ou que exista uma relação de causa e efeito entre elas
- **Cortes e máscaras (raster)**: ajusta o tamanho de um dado raster a uma área menor de interesse, geralmente definido por um dado vetorial
- **Covariável**: variável contínua que potencialmente afeta a variável resposta, mas não é necessariamente controlada ou manipulada pelo pesquisador 
- **Curva de dominância**: veja Diagrama de Whittaker
- **Dados geoespaciais**: são dados georreferenciados que expressão informações espaciais, podendo ser no formato vetorial ou matricial (raster)
- **Dados matriciais (raster)**: consistem em uma matriz (com linhas e colunas) em que os elementos representam células, geralmente igualmente espaçadas (pixels)
- **Dados tidy**: dados organizados, com foco na limpeza e organização dos mesmos, de modo que os dados estão *tidy* quando: i) variáveis estão nas colunas, ii) observações estão nas linhas e iii) valores estão nas células, sendo que para esse último, não deve haver mais de um valor por célula
- **Dados vetoriais**: são representações geométricas (pontos, linhas e polígonos) usadas para mapear fenômenos ou objetos espacialmente explícitos que possuem localização ou dimensões bem definidas, aos quais são atribuídas informações tabulares
- **Data frame**: classe de objetos que representa dados no formato de tabela, com linhas e colunas, mas comportam mais de um modo em suas colunas
- **Data Science**: nova área de conhecimento que vem se moldando a partir do desenvolvimento da sociedade em torno da era digital e da grande quantidade de dados gerados e disponíveis pela internet
- **Datum**: simplificadamente é a relação do sistema de coordenadas (geográfica ou projetada) com a superfície da Terra
- **Dendrograma**: diagrama representando uma árvore que organiza elementos, objetos e variáveis por suas semelhanças de maneira hierárquica ascendente. Desse modo, objetos mais próximos compartilham maior semelhança do que objetos distantes no dendrograma. 
- **Desagregação (raster)**: diminui o tamanho dos pixels (aumentando a resolução) de um raster, preenchendo com novos valores que depende do tipo de função de preenchimento utilizada
- **Diagrama de Whittaker**: método que utiliza informações visuais ao plotar as espécies ranqueadas no eixo X da mais abundante para a menos abundante, enquanto no eixo Y as abundâncias relativas das espécies são plotadas em escala logarítmica 
- **Diretório de trabalho**: endereço da pasta (ou diretório) de onde o R importará ou exportar dados
- **Dispersão filogenética**: espécies coexistindo nas comunidades são menos aparentadas do que esperado pelo acaso
- **Distribuição de probabilidade**: é uma função estatística que descreve todos os valores e probabilidades possíveis que uma variável aleatória pode assumir dentro de um determinado intervalo
- **Distribuição Gaussiana**: veja distribuição normal
- **Distribuição normal**: é uma distribuição de probabilidade em formato de sino que é simétrica em torno da média, mostrando que dados próximos à média são mais frequentes que dados distantes da média. 
- **Diversidade alfa**: é um conceito caracterizado pela diversidade dentro do habitat ou unidade amostral
- **Diversidade beta**: é um conceito caracterizado pela variação na diversidade entre habitats ou unidades amostrais
- **Diversidade beta filogenética**: engloba métricas que utilizam dados de presença e ausência ou abundância das espécies para determinar um valor que representa a diferença entre comunidades em relação a história evolutiva das linhagens
- **Diversidade de espécies**: é um conceito que representa o número de espécies e a distribuição de abundância destas espécies em uma comunidade 
- **Diversidade filogenética**: engloba métricas que capturam a ancestralidade compartilhada entre as espécies em termos de quantidade da história evolutiva e o grau de parentesco entre as espécies
- **Diversidade funcional**: é um conceito que captura a variação no grau de expressão de diferentes atributos funcionais entre diferentes populações, comunidades ou ecossistemas
- **Diversidade gama**: é um conceito caracterizado pela combinação da diversidade alfa e beta ou definido como a diversidade regional englobando todos os habitat ou unidades amostrais
- **Doubletons**: número de espécies observadas com abundância de dois indivíduos 
- **Duplicate**: número de espécies observadas em apenas duas amostras 
- **Equitabilidade de Pielou**: é uma métrica que descreve o padrão de distribuição da abundância relativa das espécies na comunidade
- **Erro do Tipo I**: rejeitar a hipótese nula de um teste estatístico quando ela é verdadeira 
- **Erro do Tipo II**: aceitar a hipótese nula de um teste estatístico quando ela é falsa 
- **ESRI Shapefile (vetor)**: principal formato de dados vetoriais, composto pelo menos de quatro arquivos: .shp (feição), .dbf (tabela de atributos), .shx (ligação entre .shp e .dbf) e .prj (projeção)
- **Estatística frequentista**: são análises paramétricas que estimam probabilidades das frequências observadas dos eventos e usam essas probabilidades como base para inferências. 
- **Estrutura dos objetos**: diz respeito à organização dos elementos, com relação aos modos e dimensionalidade da disposição desses elementos. De modo bem simples, os elementos podem ser estruturados em seis tipos: i) vetor, ii) fator, iii) matriz, iv) array, v) data frame e vi) listas
- **Extensão (vetor e raster)**: limites geográficos de dados geoespaciais (vetor e raster), composto por dois pares de coordenadas de longitude e de latitude
- **Extração (vetor e raster)**: identifica e retorna valores associados de pixels de um raster com base em um objeto vetorial (ponto, linha e polígono)
- **Extrapolação**: é o processo de estimar, além do intervalo de observação original, o valor de uma variável com base em sua relação com outra variável
- **Fator**: classe de objetos que representa o encadeamento de elementos de um único modo (integer) numa sequência unidimensional, representando medidas de uma variável categórica, podendo ser nominal ou ordinal
- **Fator aleatório**: pesquisador amostra aleatoriamente os níveis de um fator na população 
- **Fator fixo**: pesquisador controla todos os níveis do fator sobre os quais as inferências devem ser feitas
- **Fator de inflação da variância (VIF)**: é um teste que quantifica quanto do erro padrão dos coeficientes estimados estão inflados devido à multicolinearidade
- **Feição (vetor)**: um elemento do dado vetorial associado à cada linha da tabela de atributos
- **Fenômeno**: Um evento, entidade ou relação observável
- **Funções**: classe de objetos que possui códigos preparados para realizar uma tarefa específica de modo simples, realizando operações em argumentos
- **Generalized Least Squares (GLS)**: é um teste estatístico utilizado para estimar coeficientes desconhecidos de um modelo de regressão linear quando a variável independente é correlacionada com os resíduos 
- **GeoPackage (vetor e raster)**: banco de dados geoespacial que armazena em apenas um arquivo, dados no formato vetorial, raster e também dados não-espaciais (e.g., tabelas)
- **GeoTIFF (raster)**: principal formato para dados raster, composto geralmente de um arquivo TIFF contendo metadados geoespaciais adicionais
- **Goodness of fit**: refere-se a um teste estatístico que determina quão bem os dados da amostra se ajustam a uma distribuição de uma população 
- **Grau de liberdade**: é o número de observações nos dados que são livres para variar quando estimamos os valores dos parâmetros populacionais desconhecidos
- **Hipótese**: Afirmação testável derivada ou representando vários componentes de uma teoria
- **Hipótese alternativa (H1)**: é um conceito estatístico que sugere que diferenças entre grupos ou fenômenos medidos são maiores do que o esperado devido a variações aleatórias. A H1 é o oposto da hipótese nula. 
- **Hipótese nula (H0)**: é um conceito estatístico que sugere que diferenças entre grupos ou fenômenos medidos não são maiores do que o esperado devido a variações aleatórias. Presume-se que a hipótese nula é  verdadeira até que evidências indiquem o contrário.
- **Homocedasticidade**: é um dos pressupostos dos testes paramétricos como ANOVA, Teste T e regressão linear simples que a variância da variável dependente deve ser constante para os valores das variáveis preditoras. Sinônimo de homogeneidade da variância
- **Homogeneidade da variância**: veja homocedasticidade
- **Independência estatística**: dois eventos são independentes se a ocorrência de um evento não influenciar a probabilidade que o outro evento irá ou não ocorrer
- **Indexação (linguagem R)**: acessa elementos de objetos por sua posição utilizando os operadores [] e [[]] ou por seu nome com o operador $ depois do nome do objeto
- **Índice de diversidade**: métricas que calculam a riqueza de espécies e a distribuição de abundância para cada espécie dentro das comunidades.
- **Índice de Gini-Simpson**: métrica que quantifica a probabilidade de dois indivíduos retirados ao acaso da comunidade pertencerem a espécies diferentes. É o inverso do índice de Simpson
- **Índice de Margalef**: métrica que calcula a riqueza de espécies ponderando a abundância total dentro de cada comunidade
- **Índice de Menhinick**: métrica que calcula a riqueza de espécies ponderando a abundância total dentro de cada comunidade
- **Índice de Shannon-Wiener**: métrica de diversidade de espécies que quantifica a incerteza associada em predizer a identidade de uma espécie dado o número de espécies e a distribuição de abundância para cada espécie
- **Índice de Simpson**: métrica que quantifica a probabilidade de dois indivíduos retirados ao acaso da comunidade pertencerem à mesma espécie
- **Inf (Infinito)**: é um número muito grande ou um limite matemático
- **Interação raster-vetor**: operações derivadas da interação entre raster-vetor, como ajuste do tamanho do raster ou extração dos valores dos pixels para dados vetoriais (pontos, linhas e polígonos)
- **Interpolação**: é o processo de estimar, dentro um domínio de valores conhecidos, um valor desconhecido com base em sua relação com outra variável
- **Jackknife 1**: estimador de riqueza de espécies baseado no número de espécies que ocorrem em somente uma amostra (*uniques*)
- **Jackknife 2**: estimador de riqueza de espécies baseado no número de espécies que ocorrem em somente uma amostra (*uniques*) e no número de espécies ocorrem em exatamente duas amostras (*duplicates*)
- **Junção de tabelas**: combinação de pares de conjunto de dados tabulares por uma ou mais colunas chaves
- **Likelihood-ratio test (LRT)**: é um teste estatístico que mede o grau do ajuste (*goodness-of-fit*) entre dois modelos aninhados. Um modelo relativamente mais complexo é comparado a um modelo mais simples para ver se ele se ajusta significativamente melhor a um determinado conjunto de dados. Ele testa se há necessidade de se incluir uma variável extra no modelo para explicar os dados
- **Linguagem R**: ambiente de software livre para computação estatística e criação de gráficos
- **Lista**: classe de objetos que é tipo especial de vetor que aceita objetos como elementos
- **Loop for**: função em que um bloco de códigos é repetido mudando um contador de uma lista de possibilidades
- **Mapa**: representação bidimensional de elementos geoespaciais em uma proporção menor, podendo representar dados vetoriais ou raster, com diversos elementos visuais e textuais que facilitam a interpretação do elemento geoespacial mapeado
- **Mapas animados**: mapas que incorporam animações para expressar mudanças nos padrões espaciais ou ao longo do tempo
- **Mapas estáticos**: mapas simples e fixos para visualização de dados, sendo o tipo mais comum de saída visual
- **Mapas interativos**: mapas que incorporam a capacidade de deslocar e ampliar qualquer parte de um conjunto de dados geoespaciais sobreposto em um “mapa da web”
- **Matriz**: classe de objetos que representa elementos de um único modo no formato de tabela, com linhas e colunas
- **Máxima Verossimilhança**: é um método que determina valores para os parâmetros de um modelo. Os valores dos parâmetros são encontrados de tal forma que maximizam a probabilidade de que o processo descrito pelo modelo produza os dados que foram realmente observados
- **Mean Pairwise Distance (MPD)**: é uma métrica que utiliza a matriz de distância filogenética para quantificar a distância média do parentesco entre pares de espécies em uma comunidade
- **Mean Nearest Taxon Distance (MNTD)**: é uma métrica que utiliza a matriz de distância filogenética para quantificar a média dos valores mínimos de parentesco entre pares de espécies em uma comunidade. Ou seja, qual o valor médio da distância para o vizinho mais próximo
- **Mecanismo**: Interação direta de uma relação causal que resulta em um fenômeno
- **Modo dos objetos**: diz respeito à natureza dos elementos que compõem os dados e que foram atribuídos aos objetos. Os modos geralmente são**: numérico do tipo inteiro (integer), numérico do tipo flutuante (double), texto (character), lógico (logical) ou complexo (complex)
- **Modelo misto**: pelo menos um fator no experimento é fixo, e pelo menos um fator é aleatório.
- **Modelo nulo**: é um procedimento estatístico que usa aleatorizações para gerar distribuições de valores para uma determinada variável de interesse na ausência do processo causal em questão
- **Multicolinearidade**: é um conceito estatístico onde variáveis independentes em um modelo são correlacionadas
- **NA (Not Available)**: significa dado faltante ou indisponível
- **NaN (Not a Number)**: representa indefinições matemáticas
- **Nearest Relative Index (NRI)**: métrica que calcula o tamanho do efeito padronizado para a métrica *Mean Pairwise Distance*.Valores positivos de NRI indicam agrupamento filogenético enquanto valores negativos de NRI indicam dispersão filogenética
- **Nearest Taxon Index (NTI)**: métrica que calcula o tamanho do efeito padronizado para a métrica *Mean Nearest Taxon Distance*.Valores positivos de NTI indicam agrupamento filogenético enquanto valores negativos de NTI indicam dispersão filogenética
- **NetCDF (raster)**: Network Common Data Form é um conjunto de bibliotecas de software e formatos de dados independentes que suportam a criação, acesso e compartilhamento de dados científicos orientados a arrays
- **Nó**: o ponto onde uma linhagem dá origem a duas ou mais linhagens descendentes
- **Normalidade dos resíduos**: é um dos pressupostos dos testes paramétricos como ANOVA, Teste T e regressão linear simples que dependem que os resíduos do modelo apresentem distribuição normal ou gaussiana.
- **NULL (Nulo)**: representa um objeto nulo, sendo útil para preenchimento em aplicações de programação
- **Números de Hill**: é uma métrica que transforma a riqueza e a distribuição da abundância das espécies em números efetivos de espécies ou diversidade verdadeira
- **Número efetivo de espécies**: é o número de espécies igualmente abundantes (i.e. todas as espécies com a mesma abundância) necessárias para produzir o valor observado para um determinado índice
- **Objetos**: palavras às quais são atribuídos dados através da atribuição. A criação de objetos possibilita a manipulação de dados ou armazenar os resultados de análises. Em outras linguagens de programação são denominadas variáveis
- **Operações geoespaciais**: são operações para acessar ou alterar as propriedades não-espaciais, espaciais e geométricas dos dados geoespaciais, divididas em**: operações de atributos, operações espaciais e operações geométricas
- **Operações geoespaciais de atributos**: modificação de objetos geoespaciais baseado em informações não espaciais associadas a dados geoespaciais, como a tabela de atributos ou valores das células e nome das camadas dos rasters
- **Operações geoespaciais espaciais**: modificações de objetos geoespaciais baseado em informações espaciais, como localização e formato
- **Operações geoespaciais geométricas**: modificações em objetos geoespaciais baseado na geometria do vetor ou do raster e na interação e conversão entre vetor-raster
- **Operadores**: conjuntos de caracteres que realiza operações, agrupados em cinco tipos principais**: aritméticos, relacionais, lógicos, atribuição e diversos
- **Pacotes (linguagem R)**: conjuntos extras de funções para executar tarefas específicas
- **Padrão**: Eventos repetidos, entidades recorrentes ou relações replicadas no tempo ou no espaço
- **Phylogenetic Diversity (PD)**: é uma métrica definida pela soma do comprimento dos ramos conectando todas as espécies na comunidade
- **Phylogenetic Endemism (PE)**: é uma métrica que calcula a fração dos ramos restritos a regiões específicas
- **Phylogenetic index of beta diversity (Phylosor)**: métrica de similaridade que determina o comprimento total dos ramos da filogenia que é compartilhado entre pares de comunidades
- **Phylogenetic Species Richness (PSR)**: é uma métrica diretamente comparável ao número de espécies na comunidade, mas inclui o parentesco filogenético entre as espécies
- **Phylogenetic Species Variability (PSV)**: é uma métrica que estima a quantidade relativa dos comprimentos dos ramos não compartilhados entre as comunidades
- **Pipe (%>%)**: operador implementado por uma função que faz com o que o resultado de uma função seja o primeiro argumento da função seguinte, permitindo o encadeamento de várias funções eliminando a necessidade de criar objetos para armazenar resultados intermediários
- **Pivotagem de dados**: transporte de dados que estão em linhas para colunas e vice-versa, fazendo a referência cruzada ou rotacionando os dados. Partirmos de dados no formato longo (long, muitas linhas e poucas colunas) e criamos dados no formato largo (wide, poucas linhas e muitas colunas) e vice-versa
- **Pixel (raster)**: também chamado célula, é a unidade geoespacial do raster, representando o elemento da matriz de dados
- **Polígono convexo**: operação que liga os pontos externos de um conjunto de pontos e cria um polígono a partir deles
- **Polígono de Voronoi**: polígonos irregulares são criados a partir da proximidade dos pontos, de modo a estimar uma área de abrangência no entorno dos mesmos
- **Politomia**: três ou mais linhagens descendendo de um único nó
- **População**: é um conjunto de indivíduos ou elementos semelhantes que interessa para alguma pergunta ou hipótese
- **População amostral**: é um conjunto de indivíduos ou elementos semelhantes que estão de fato acessível para serem amostrados
- **Predição espacial**: utiliza os coeficientes de um modelo ajustado para gerar um raster de predição para todos os pixels considerando os dados preditores de entrada do modelo, extrapolando a predição da resposta
- **Predição**: uma declaração de expectativa deduzida da estrutura lógica ou derivada da estrutura causal de uma teoria
- **Pressuposto**:	condições necessárias para sustentar uma hipótese ou construção da teoria
- **Principais elementos de um mapa**: um mapa possui diversos elementos que facilitam sua interpretação, dentre eles: i) mapa principal, ii) mapa secundário iii) título, iv) legenda (apresentando as informações detalhadas das classes ou escala de valores, v) barra de escala, vi) indicador de orientação (Norte), vii) gride de coordenadas e viii) descrição do CRS
- **Processo**: um subconjunto de fenômenos em que os eventos seguem uns aos outros no tempo ou espaço, que podem ou não serem causalmente conectados. É a causa, mecanismo ou limitação explicando um padrão
- **Programação Funcional**: organização do código como funções e variáveis que trabalham de forma unificada para a resolução de um problema
- **Projeto do RStudio**: arquivo no formato .Rproj que facilita o trabalho com o RStudio, pois define o diretório automaticamente e permite o controle de versão
- **Raiz**: representa o ancestral comum de todas as espécies na filogenia
- **Ramo**: uma linha orientada ao longo de um eixo terminais-raiz que conecta os nós na filogenia
- **Rarefação**: é uma métrica usada para calcular o número esperado de espécies em cada comunidade tendo como base comparativa um valor em que todas as amostras ou número de indivíduos atinjam um tamanho padrão entre as comunidades
- **Rarefação baseada nas amostras (Sampled-based)**: as comparações são padronizadas pela comunidade com menor número de amostragens
- **Rarefação baseada na cobertura (Coverage-based)**: é uma medida que determina a proporção de amostras ou do número de indivíduos da comunidade que representa as espécies amostradas
- **Rarefação baseada nos indivíduos (Individual-based)**: as comparações são feitas considerando a abundância da comunidade padronizada pelo menor número de indivíduos
- **Rasterização**: conversão de dados vetoriais para raster realizada de pontos, linhas ou polígonos para rasters
- **Regressão**: é um teste usado para analisar a relação entre uma ou mais variáveis preditoras (Xn) e uma variável resposta (Y). A regressão assume uma relação de causa e efeito entre as variáveis
- **Reprojeção**: transformação do Sistema de Referência de Coordenadas (CRS) de um dado geoespacial, alterando o CRS original para outro. Na reprojeção alteramos tanto a unidade do dado geoespacial mudando o Sistema de Coordenadas Geográficas (unidades em ‘longitude/latitude’) para Projetado (unidades de metros, e vice-versa), quando o Datum
- **Resíduo**: é a diferença entre os valores predito e observado dos dados. São também chamados de erro
- **Resolução (raster)**: termo amplo que pode ser usado em diversos contextos. Para dados raster, é geralmente associado ao tamanho (dimensão) do pixel (i.e., altura e largura)
- **RStudio**: ambiente de desenvolvimento integrado (IDE) para R. Inclui um console, editor de realce de sintaxe que suporta execução direta de código, bem como ferramentas para plotagem, histórico, depuração e gerenciamento de espaço de trabalho
- **Script (RStudio)**: arquivos de texto simples, criados com a extensão (terminação) .R onde os códigos são escritos e salvos
- **Seleção de modelos**: é um processo usado para comparar o valor relativo de diferentes modelos estatísticos e determinar qual deles é o mais adequado para os dados observados
- **Série de Hill**: veja Número de Hill
- **Singleton**: número de espécies observadas com abundância de um indivíduo 
- **Sistema de Coordenadas**: composto por dois sistemas, o Sistema de Coordenadas Geográficas e o Sistema de Coordenadas Projetadas, que utilizam duas unidades ângulos ou metros, respectivamente, para a representação geográfica
- **Sistema de Referência de Coordenadas (CRS)**: também chamada projeção, define a referência geoespacial dos dados vetor e raster na superfície da Terra, composto pelo Sistema de Coordenadas e Datum
- **Tabela de atributos**: dado tabular que inclui dados geoespaciais e dados alfanuméricos, geralmente associada a dados vetoriais
- **Terminal (do inglês tip)**: o final do ramo representando uma espécie atual ou extinta (pode também representar gêneros, indivíduos, genes, etc.)
- **Teste de Levene**: é um teste estatístico utilizado para verificar a homogeneidade da variância entre dois ou mais grupos
- **Teste de Shapiro-Wilk**: é um teste estatístico utilizado para verificar se os dados apresentam distribuição normal
- **Teste T (de Student)**:  é um teste estatístico que segue uma distribuição t de Student para rejeitar ou não uma hipótese nula de médias iguais entre dois grupos.
- **Teste T pareado**:  é um teste estatístico que usa dados medidos duas vezes na mesma unidade amostral, resultando em pares de observações para cada amostra (amostras pareadas). Ele determina se a diferença da média entre duas observações é zero..
- **Tibble**: classe de objetos que é uma versão aprimorada do data frame. É a classe aconselhada para que as funções do *tidyverse* funcionem melhor sobre conjuntos de dados tabulares
- **tidyverse**: “dialeto novo” para a linguagem R, onde tidy quer dizer organizado, arrumado, ordenado, e *verse* é universo. Operacionalizado no R através de uma coleção de pacotes que atuam no fluxo de trabalho comum da ciência de dados: importação, manipulação, exploração, visualização, análise e comunicação de dados e análises. O principal objetivo do *tidyverse* é aproximar a linguagem para melhorar a interação entre ser humano e computador sobre dados, de modo que os pacotes compartilham uma filosofia de design de alto nível e gramática, além da estrutura de dados de baixo nível
- **Ultramétrica**: a distância de todos os terminais até a raiz são idênticas. Característica requerida pela maioria dos índices de diversidade filogenética
- **Unidade amostral**: é o indivíduo (ou elemento) da população amostral sobre o qual a medida de interesse será observada
- **Unique**: número de espécies observadas em apenas uma amostra
- **Unique Fraction metric (UniFrac)**: métrica de dissimilaridade que determina a fração única da filogenia contida em cada uma das duas comunidades
- **Valor de P**: probabilidade de um teste estatístico ser igual ou maior que o observado, dado que a hipótese nula é verdadeira.
- **Valores faltantes e especiais**: valores reservados que representam dados faltantes, indefinições matemáticas, infinitos e objetos nulos
- **Variance of Pairwise Distance (VPD)**: é uma métrica que utiliza a matriz de distância filogenética para quantificar a variância do parentesco entre pares de espécies em uma comunidade
- **Variável categórica**: são variáveis que não possuem valores quantitativos e são definidas por categorias ou grupos distintos
- **Variável contínua**: são variáveis numéricas que têm um número infinito de valores entre dois valores quaisquer. Neste caso, valores fracionais fazem sentido
- **Variável dependente**: é uma variável mensurada ou observada de interesse do pesquisador que depende do valor de outra variável
- **Variável discreta**: é uma variável numérica que têm um número contável de valores inteiros. 
- **Variável explicativa**: ver variável independente
- **Variável independente**: variável mensurada ou observada pelo pesquisador que prevê ou afeta a variável dependente
- **Variável nominal**: são variáveis categóricas que não apresentam ordenação dentre as categorias (e.g., preto, branco e rosa)
- **Variável ordinal**: são variáveis categóricas com ordenação entre as categorias (e.g., pequeno, médio e grande) 
- **Variável preditora**: ver variável independente
- **Variável resposta**: ver variável dependente
- **Variograma**: é uma descrição da continuidade espacial dos dados. Ele mede a variabilidade entre pares de pontos em várias distâncias
- **Vetor**: classe de objetos que representa o encadeamento de elementos de um único modo numa sequência unidimensional
- **Vetorização (vetor)**: conversão de dados rasters para vetor, sendo que esse vetor receberá os valores dos pixels do raster, podendo ser convertido em pontos, isolinhas ou polígonos

